catalog/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

urlpatterns = [
    path('', views.index, name='index'),
    path('yeasts/', views.YeastListView.as_view(), name='yeasts'),
    path('yeast/<int:pk>', views.YeastDetailView.as_view(), name='yeast-detail'),
    path('yeast/create/', views.YeastCreate.as_view(), name='yeast-create'),
    path('yeast/<int:pk>/update', views.YeastUpdate.as_view(), name='yeast-update'),
    path('yeast/<int:pk>/delete', views.YeastDelete.as_view(), name='yeast-delete'),
    path('storage/', views.storageList, name='storage'),
    path('storage/<int:pk>', views.StorageInstanceDetailView.as_view(), name='storageinstance-detail'),
    path('storage/create/', views.create_storage_instance, name='storageinstance-create'),
    path('storage/<int:pk>/update', views.update_storage_instance, name='storageinstance-update'),
    path('storage/<int:pk>/delete', views.StorageInstanceDelete.as_view(), name='storageinstance-delete'),
    path('media/', views.MediaListView.as_view(), name='media'),
    path('media/<int:pk>', views.MediaDetailView.as_view(), name='media-detail'),
    path('media/create/', views.MediaCreate.as_view(), name='media-create'),
    path('media/<int:pk>/update', views.MediaUpdate.as_view(), name='media-update'),
    path('media/<int:pk>/delete', views.MediaDelete.as_view(), name='media-delete'),
    path('docs/', views.testdocument, name='test-document'),
]

yeast/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include # Use include() to add paths from the catalog application
from django.views.generic import RedirectView #Add URL maps to redirect the base URL to our application
from django.conf import settings
from django.conf.urls.static import static # Use static() to add url mapping to serve static files during development (only)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', RedirectView.as_view(url='/catalog/')),    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/models.py
from django.core import serializers
from django.db import models
from django.db.models import Count
from django.contrib.auth.models import User
from django.urls import reverse
from datetime import date
# import sys for debugging - saving JSON serialise
import sys

# Create your models here.

class Yeast(models.Model):
    """
    Model representing a yeast strain in the catalog
    """

    name = models.CharField(max_length=100, help_text="Enter the name of the yeast strain")

    TYPE_LIST = (
        ("Ale", "Ale"),
        ("Lager", "Lager"),
        ("Cider","Cider"),
        ("Champagne","Champagne"),
        ("Wine","Wine"),
    )

    yeast_type = models.CharField(max_length=10, choices=TYPE_LIST, blank=True, help_text='Yeast type')
    comments = models.CharField(max_length=255, help_text="Enter comments (up to 255 characters)")
    attenuation = models.PositiveSmallIntegerField(null=True)
    # Need to add logic to check upper temp is higer than lower temp when either is provided. Do this in form
    upper_temp = models.PositiveSmallIntegerField(null=True)
    lower_temp = models.PositiveSmallIntegerField(null=True)
    
    FLOC_LIST = (
        ('L', 'Low'),
        ('M', 'Moderate'),
        ('H', 'High'),
    )

    flocculation = models.CharField(max_length=1, choices=FLOC_LIST, blank=True, help_text='Yeast flocculation')
    # This logic should be used in a dynamic list box, with list options based on yeast_type selected - do in form
    CHARACTER_LIST = (
        ('Clean','Clean'),
        ('Fruity','Fruity'),
        ('Hybrid','Hybrid'),
        ('Phenolic','Phenolic'),
        ('Eccentric','Eccetric'),
        ('Dry','Dry'),
        ('Full','Full'),
    )
    
    character = models.CharField(max_length=10, choices=CHARACTER_LIST, blank=True, help_text='Yeast category')
    tolerance = models.PositiveSmallIntegerField(null=True)
    
    class Meta:
        ordering = ['name']

    def __str__(self):
        """
        String for representing the Model object (in Admin site etc.)
        """
        return '{0} ({1})'.format(self.name,self.yeast_type)

    def get_absolute_url(self):
        """
        Returns the url to access a particular yeast instance
        """
        return reverse('yeast-detail', args=[str(self.id)])

    def get_yeast_count(self):
        """
        Returns the count of storage instances available with the yeast strain
        """
        available_yeast_count = self.storageinstance_set.filter(storage_status='i').count()
        return available_yeast_count
    
    def get_inoculated_list(self):
        """
        Returns a list of available storage instances inoculated with a yeast
        """
        inoculated_storage_list = self.storageinstance_set.filter(storage_status='i')
        return inoculated_storage_list

    def get_used_list(self):
        """
        Returns a list of used storage instances inoculated with a yeast 
        """
        used_storage_list = self.storageinstance_set.filter(storage_status='u')
        return used_storage_list

class Media(models.Model):
    """
    Model representing the types of growth media yeast can be grown and stored on
    """

    name = models.CharField(max_length=100, help_text='Enter the name for the media')
    date_created = models.DateField(null=True, blank=True)

    MEDIA_TYPE = (
        ('a','Agar'),
        ('w','Wort'),
        ('g','Glycerin'),
        ('sc','Sodium chloride'),
        ('g','Gelatine'),
    )

    media_type = models.CharField(max_length=100,choices=MEDIA_TYPE, help_text='Select the appropriate media type')
    volume = models.PositiveSmallIntegerField(null=True, help_text="Enter the total volume of media created")
    gravity = models.PositiveSmallIntegerField(null=True, help_text="Enter the gravity of media created")
    comments = models.CharField(max_length=255, help_text="Enter comments (up to 255 characters)")

    class Meta:
        ordering = ['date_created']
        verbose_name_plural = 'Media'

    def __str__(self):
        """
        String for representing the Model object (in Admin site etc.)
        """
        return '{0} ({1}) - {2}'.format(self.name,self.get_media_type_display(),self.date_created)

    def get_absolute_url(self):
        """
        Returns the url to access a particular media.
        """
        return reverse('media-detail', args=[str(self.id)])

    def get_inoculated_list(self):
        """
        Returns a list of inoculated storage instances using a particular media.
        """
        inoculated_storage_list = self.storageinstance_set.filter(storage_status='i')
        return inoculated_storage_list

    def get_available_list(self):
        """
        Returns a list of available storage instances using a particular media.
        """
        available_storage_list = self.storageinstance_set.filter(storage_status='a')
        return available_storage_list

    def get_used_list(self):
        """
        Returns a list of used/discarded storage instances using a particular media.
        """
        used_storage_list = self.storageinstance_set.filter(storage_status='u')
        return used_storage_list

class StorageInstance(models.Model):
    """
    Model representing each instance of storage in the catalog
    """

    yeast = models.ForeignKey('Yeast', on_delete=models.SET_NULL, blank=True, null=True)
    # need to put some logic here that a storage instance can't have itself as a parent
    parent = models.ForeignKey('self', on_delete=models.SET_NULL, blank=True, null=True)
    date_created = models.DateField(null=True)
    date_inoculated = models.DateField(null=True, blank=True)

    STORAGE_TYPE_LIST = (
        ('s','Slant'),
        ('p','Plate'),
        ('sol','Solution'),
        ('f','Freeze'),
        ('o','Other'),
    )

    storage_type = models.CharField(max_length=100,choices=STORAGE_TYPE_LIST, help_text='Select the appropriate yeast storage category')
    media = models.ForeignKey('Media', on_delete=models.SET_NULL, null=True)

    STORAGE_STATUS_LIST = (
        ('u','Used / Discarded'),
        ('i','Inoculated'),
        ('a','Available'),
    )
    
    storage_status = models.CharField(max_length=100,choices=STORAGE_STATUS_LIST, help_text='Select the appropriate media type')
    comments = models.CharField(max_length=255, help_text="Enter comments (up to 255 characters)")

    class Meta:
        ordering = ['id']

    def __str__(self):
        """
        String for representing the Model object (in Admin site etc.)
        """
        # might add some more logic here - if inoculated, then pass yeast type and date inoculated in return else return the string below
        return '{0} ({1}) - {2}'.format(self.id, self.get_storage_type_display(), self.get_storage_status_display())
    
    #Need to write a method that generates a queryset with related storage instances and serialises the queryset_
    # to a JSON object. This object can then be passed to the browser to render the tree diagram showing the yeast's lineage_
    # Note this only needs to cover inoculated yeasts
    def create_JSON_relatives(self):
        #create the queryset to serialises 
        # move this into serialise statement once confirmed working
        relative_set = StorageInstance.objects.filter(yeast=self.yeast)
        #serialise statement
        serial_data = serializers.serialize('json', relative_set, fields=('id','parent'))
        print(serial_data)
        f = open("out.json",'w')
        f.write(serial_data)
        f.close

    def get_absolute_url(self):
        """
        Returns the url to access a particular storage instance.
        """
        return reverse('storageinstance-detail', args=[str(self.id)])

catalog/forms.py
from django import forms
from django.forms import ModelForm, IntegerField, Textarea
from .models import Yeast, Media, StorageInstance
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
import datetime #for checking inoculated date is after created.

class CreateStorageInstanceForm(forms.ModelForm):
    """
    Form for creating new storage instances
    """
    #Form variables
    storageinstance_count = IntegerField(label='Number of storage items created',help_text='Must be an integer greater than zero',min_value=1) 

    def clean_storageinstance_count(self):
        data = self.cleaned_data['storageinstance_count']

        #Check if count if >=1
        if data < 1:
            raise ValidationError(_('Number of storage instances must be 1 or more'))

        return data

    class Meta:
        model = StorageInstance
        fields = '__all__'
        exclude = ('parent','date_inoculated',)

class UpdateStorageInstanceForm(forms.ModelForm):
    """
    Form for updating an existing storage instance
    """
    #Remove self from foreign key list to prevent referencing self as a parent
    #Need to limit query set to only storage instances with the same yeast strain
    #JS in the browser is the best way to do this - pass the complete dropdown list to the broswer (code below works fine)_
    #Then filter the list dynamically when the user selects an item from the "Yeast" listbox on the form to_
    #filter the listbox source list based on the selected "Yeast"
    def __init__(self, *args, **kwargs):
            super(UpdateStorageInstanceForm, self).__init__(*args, **kwargs)
            self.fields['parent'].queryset = StorageInstance.objects.exclude(id__exact=self.instance.id)
    
    class Meta:
        model = StorageInstance
        fields = '__all__'

catalog/views.py
from django.shortcuts import render, render_to_response, get_object_or_404
from django.views import generic
from django.urls import reverse, reverse_lazy
from .models import Yeast, Media, StorageInstance
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic import TemplateView
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.decorators import permission_required, login_required
from .forms import CreateStorageInstanceForm, UpdateStorageInstanceForm
import datetime #to set initial value of date field to today

# Create your views here.

def index(request):
    """
    View function for home page of application.
    """
    return render(
        request,
        'index.html',
    )

class YeastListView(generic.ListView):
    model = Yeast

class YeastDetailView(generic.DetailView):
    model = Yeast

class YeastCreate(PermissionRequiredMixin, CreateView):
    model = Yeast
    fields = '__all__'
    permission_required = 'catalog.is_staff'

class YeastUpdate(PermissionRequiredMixin, UpdateView):
    model = Yeast
    fields = '__all__'
    permission_required = 'catalog.is_staff'

class YeastDelete(PermissionRequiredMixin, DeleteView):
    model = Yeast
    success_url = reverse_lazy('yeasts')
    permission_required = 'catalog.is_staff'

def storageList(request):
    """
    View function for storage instance list
    """
    list_storage_inoculated=StorageInstance.objects.filter(storage_status__exact='i')
    list_storage_available=StorageInstance.objects.filter(storage_status__exact='a')
    list_storage_used=StorageInstance.objects.filter(storage_status__exact='u')

    return render(
        request,
        'catalog/storageinstance_list.html',
        context={
            'list_storage_inoculated':list_storage_inoculated,
            'list_storage_available':list_storage_available,
            'list_storage_used':list_storage_used},
    )

class StorageInstanceDetailView(generic.DetailView):
    model = StorageInstance

@login_required
@permission_required('catalog.can_add_storageinstance')
def create_storage_instance(request):
    """
    View function for creating storage instances
    """

    today = datetime.datetime.today().strftime('%Y-%m-%d')
    create_list = []

    # If this is a POST request then process the Form data
    if request.method == 'POST':

        # Create a form instance and populate it with data from the request (binding):
        form = CreateStorageInstanceForm(request.POST)

        # Check if the form is valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            create_list = [StorageInstance(
                date_created=form.cleaned_data['date_created'],
                storage_type=form.cleaned_data['storage_type'],
                media=form.cleaned_data['media'],
                storage_status=form.cleaned_data['storage_status'],
                comments=form.cleaned_data['comments'],
            )

                for i in list(range(0,form.cleaned_data['storageinstance_count']))]
            # bulk create of StorageInstance objects based on counter from form
            StorageInstance.objects.bulk_create(create_list)
            # redirect to a new URL:
            return HttpResponseRedirect(reverse('storage'))

    # If this is a GET (or any other method) create the default form.
    else:
        form = CreateStorageInstanceForm(
            initial={
                'date_created':today,
                'storage_status':'a',
                'storageinstance_count':1
            }
        )

    return render(
        request,
        'catalog/storageinstance_create.html',
        {'form':form}
    )

@login_required
@permission_required('catalog.can_add_storageinstance')
def update_storage_instance(request, pk):
    """
    View function for updating storage instances
    """

    # If this is a POST request then process the Form data
    if request.method == 'POST':

        # Create a form instance and populate it with data from the request (binding):
        form = UpdateStorageInstanceForm(request.POST)

        # Check if the form is valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required

            return HttpResponseRedirect(reverse('storage'))

    # If this is a GET (or any other method) create the default form.
    else:
        storage_instance = StorageInstance.objects.get(pk=pk)
        form = UpdateStorageInstanceForm(
            instance=storage_instance
        )

    return render(
        request,
        'catalog/storageinstance_form.html',
        {'form':form}
    )
    
class StorageInstanceDelete(PermissionRequiredMixin, DeleteView):
    model = StorageInstance
    success_url = reverse_lazy('storage')
    permission_required = 'catalog.is_staff'
    
class MediaListView(generic.ListView):
    model = Media

class MediaDetailView(generic.DetailView):
    model = Media

class MediaCreate(PermissionRequiredMixin, CreateView):
    model = Media
    fields = '__all__'
    permission_required = 'catalog.is_staff'

class MediaUpdate(PermissionRequiredMixin, UpdateView):
    model = Media
    fields = '__all__'
    permission_required = 'catalog.is_staff'

class MediaDelete(PermissionRequiredMixin, DeleteView):
    model = Media
    success_url = reverse_lazy('media')
    permission_required = 'catalog.is_staff'

def testdocument(request):
    return render(
        request,
        'catalog/test_doc.html',
    )

catalog/templates/catalog/media_confirm_delete.html
{% extends "base_detail.html" %}

{% block detail %}
<h1>Delete Media</h1>
<p>Are you sure you want to delete this media: {{ media }}?</p>
<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" action="" value="Yes, delete." />
</form>
{% endblock %}

catalog/templates/catalog/media_detail.html
{% extends "base_detail.html" %}

{% block detail %}
<p><a href="{% url 'index' %}">Home</a> > <a href="{% url 'media' %}">Media List</a> ></p>
  <h1>Name: {{ media.name }}</h1>
  {% if user.is_authenticated %}
  <div class="btn-toolbar">
    <a class="btn btn-primary" role="button" href="{% url 'media-update' media.pk %}">Update media</a>
    <a class="btn btn-primary" role="button" href="{% url 'media-delete' media.pk%}">Delete media</a>
  </div>
  {% endif %}
<div class="table-responsive">
  <table class="table table-borderless table-sm">
    <tbody>
      <tr>
        <td style="width: 50%"><strong>Type:</strong> {{ media.get_media_type_display }}</td>
        <td style="width: 50%"><strong>Volume:</strong> {{ media.volume }}</td>
      </tr>
      <tr>
        <td style="width: 50%"><strong>Date Created:</strong> {{ media.date_created }}</td>
        <td style="width: 50%"><strong>Gravity:</strong> {{ media.gravity }}</td>
      </tr>
    </tbody>
  </table>
  <hr>
</div>
<p><strong>Comments:</strong> {{ media.comments }}</p>
 
<h3>Storage Instances</h3>

<div class="container">
  <ul id="mediatabs" class="nav nav-tabs">
    <li><a class="nav-link active" role="tab" href="#inoculated" data-toggle="tab">Inoculated</a>
    <li><a class="nav-link" role="tab" href="#available" data-toggle="tab">Available</a>
    <li><a class="nav-link" role="tab" href="#used" data-toggle="tab">Used</a>
  </ul> 

  <div class="tab-content">
    <div id="inoculated" class="tab-pane fade show active">
      <table class="table">
        <thead class="thead-dark">
          <tr>
            <th>Storage ID</th>
            <th>Storage Type</th>
            <th>Yeast</th>
            <th>Date Created</th>
            <th>Date Inoculated</th>
          </tr>
        </thead>
        <tbody>
          {% if media.get_inoculated_list %}
            {% for storageinstance in media.get_inoculated_list %}
            <tr>
              <td><a href="{% url 'storageinstance-detail' storageinstance.pk %}">{{ storageinstance.id }}</a></td>
              <td>{{ storageinstance.get_storage_type_display }}</td>
              <td><a href="{% url 'yeast-detail' storageinstance.yeast.pk %}">{{ storageinstance.yeast.name }}</a></td>
              <td>{{ storageinstance.date_created }}</td>
              <td>{{ storageinstance.date_inoculated }}</td>
            </tr>
            {% endfor %}
          {% else %}
            <tr>
              <td colspan="3">No inocualted storage with this media</td>
            <tr>
          {% endif %}
        </tbody>
      </table>
    </div>

    <div id="available" class="tab-pane fade">
      <table class="table">
        <thead class="thead-dark">
          <tr>
            <th>Storage ID</th>
            <th>Storage Type</th>
            <th>Date Inoculated</th>
          </tr>
        </thead>
        <tbody>
          {% if media.get_available_list %}
            {% for storageinstance in media.get_available_list %}
            <tr>
              <td><a href="{% url 'storageinstance-detail' storageinstance.pk %}">{{ storageinstance.id }}</a></td>
              <td>{{ storageinstance.get_storage_type_display }}</td>
              <td>{{ storageinstance.date_inoculated }}</td>
            </tr>
            {% endfor %}
          {% else %}
            <tr>
              <td colspan="3">No inocualted storage with this media</td>
            <tr>
          {% endif %}
        </tbody>
      </table>
    </div>

      <div id="used" class="tab-pane fade">
        <table class="table">
          <thead class="thead-dark">
            <tr>
              <th>Storage ID</th>
              <th>Storage Type</th>
              <th>Date Inoculated</th>
            </tr>
          </thead>
          <tbody>
            {% if media.get_used_list %}
              {% for storageinstance in media.get_used_list %}
              <tr>
                <td><a href="{% url 'storageinstance-detail' storageinstance.pk %}">{{ storageinstance.id }}</a></td>
                <td>{{ storageinstance.get_storage_type_display }}</td>
                <td>{{ storageinstance.date_inoculated }}</td>
              </tr>
              {% endfor %}
            </ul>
          {% else %}
            <tr>
              <td colspan="3">No used storage with this media</td>
            <tr>
          </ul>
          {% endif %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
{% endblock %}

catalog/templates/catalog/media_form.html
{% extends "base_form.html" %}

{% block form %}

<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />

</form>
{% endblock %}

catalog/templates/catalog/media_list.html
{% extends "base_list.html" %}

{% block list %}
<p><a href="{% url 'index' %}">Home</a> ></p>
<h1>Media List</h1>
{% if user.is_authenticated %}
<nav>  
  <a class="btn btn-primary" role="button" href="{% url 'media-create' %}">Add new media</a>
</nav>
{% endif %}

<div class="container">
  <table class="table table-hover">
    <thead class="thead-dark">
      <tr>
        <th>Name</th>
        <th>Date Created</th>
        <th>Type</th>
        <th>Volume</th>
        <th>Gravity</th>
      </tr>
    </thead>
    <tbody>
{% if media_list %}
{% regroup media_list|dictsort:"media_type" by get_media_type_display as media_type_list %}
    {% for media_type in media_type_list %}
      <thead class="thead-light">
        <tr>
          <th colspan="9">{{ media_type.grouper }}</th>
        </tr>
      </thead>
      {% for media in media_type.list %}
      <tr>
          <td><a href="{{ media.get_absolute_url }}">{{ media.name }}</a></td>
          <td>{{ media.date_created }}</td>
          <td>{{ media.get_media_type_display }}</td>
          <td>{{ media.volume }}</td>
          <td>{{ media.gravity }}</td>
      </tr>
      {% endfor %}
    {% endfor %}
    {% else %}
    <tr>
      <td>No media in the catalogue.</td>
    </tr>
    {% endif %}
</div>
{% endblock %}

catalog/templates/catalog/storageinstance_confirm_delete.html
{% extends "base_detail.html" %}

{% block detail %}

<h1>Delete Storage</h1>

<p>Are you sure you want to delete this storage: {{ yeast }}?</p>

<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" action="" value="Yes, delete." />
</form>

{% endblock %}

catalog/templates/catalog/storageinstance_create.html
{% extends "base_form.html" %}

{% block form %}

<form action="" method="post">
    {% csrf_token %}

<div class="table-responsive">
  <table class="table table-borderless table-sm">
    {{ form }}
  </table>
</div>

<div class="btn-toolbar">
  <input class="btn btn-primary" role="button" type="submit" value="Create Storage" />
  <input type="hidden" name="next" value="{{ next }}" />
</div>
</form>

 <script>
  $(function() {
    $( ".datepicker" ).datepicker({
      changeMonth: true,
      changeYear: true,
      yearRange: "1900:2050",
      // You can put more options here.

    });
  });
  </script>
{% endblock %}

catalog/templates/catalog/storageinstance_form.html
{% extends "base_form.html" %}

{% block form %}

<form action="" method="post">
    {% csrf_token %}

<div class="table-responsive">
  <table class="table table-borderless table-sm">
    {{ form }}
  </table>
<div>

<div class="btn-toolbar">
  <input class="btn btn-primary" role="button" type="submit" value="Update Storage" />
  <input type="hidden" name="next" value="{{ next }}" />
</div>

</form>

 <script>
  $(function() {
    $( ".datepicker" ).datepicker({
      changeMonth: true,
      changeYear: true,
      yearRange: "1900:2020",
      // You can put more options here.

    });
  });
  </script>
</form>
{% endblock %}

catalog/templates/catalog/test_doc.html
{% extends "base_list.html" %}
{% block list %}
<p>Things to do...</p>
<ul>
    <li>Complete writing tests...are they ever complete?</li>
    <li>Include option to select parent for inoculated storage (needs some form validation to prevent a storage instance selecting itself as a parent)</li>
    <li>Model pop-up for creating media and yeast from storage instance - see Django admin for examples</li>
    <li>Family tree - passing nodes to JavaScript library to render family tree for each storage instance</li>
    <li>Include yeast maintenance section - flag old inoculated storage instances and yeasts that are down to <=2 inoculated storage instances</li>
    <li>Update landing page</li>
</ul>
{% endblock %}

catalog/templates/catalog/yeast_detail.html
{% extends "base_detail.html" %}

{% block detail %}
<p><a href="{% url 'index' %}">Home</a> > <a href="{% url 'yeasts' %}">Yeast List</a> ></p>
  <h1>Yeast: {{ yeast.name }}</h1>
  {% if user.is_authenticated %}
  <div class="btn-toolbar">
    <a class="btn btn-primary" role="button" href="{% url 'yeast-update' yeast.pk %}">Update yeast</a>
    <a class="btn btn-primary" role="button" href="{% url 'yeast-delete' yeast.pk %}">Delete yeast</a>
  </div>
  {% endif %}
<div class="table-responsive">
  <table class="table table-borderless table-sm">
    <tbody>
      <tr>
        <td style="width: 50%"><strong>Type:</strong> {{ yeast.yeast_type }}</td>
        <td style="width: 50%"><strong>Category:</strong> {{ yeast.get_character_display }}</td>
      </tr>
      <tr>
        <td style="width: 50%"><strong>Attenuation:</strong> {{ yeast.attenuation }}</td>
        <td style="width: 50%"><strong>Flocculation:</strong> {{ yeast.get_flocculation_display }}</td>
      </tr>
      <tr>
        <td style="width: 50%"><strong>Alcohol Tolerance:</strong> {{ yeast.tolerance }}</td>
      </tr>
    </tbody>
  </table>
  <hr>
</div>
  <p><strong>Comments:</strong> {{ yeast.comments }}</p>
  <hr>
  <h3>Yeast Instances</h3>

<div class="container">
  <ul id="yeasttabs" class="nav nav-tabs">
    <li><a class="nav-link active" role="tab" href="#inoculated" data-toggle="tab">Inoculated</a>
    <li><a class="nav-link" role="tab" href="#used" data-toggle="tab">Used</a>
  </ul> 

  <div class="tab-content">
    <div id="inoculated" class="tab-pane fade show active">
      <table class="table">
        <thead class="thead-dark">
          <tr>
            <th>Storage ID</th>
            <th>Storage Type</th>
            <th>Date Inoculated</th>
          </tr>
        </thead>
        <tbody>
          {% if yeast.get_inoculated_list %}
            {% for storageinstance in yeast.get_inoculated_list %}
            <tr>
              <td><a href="{% url 'storageinstance-detail' storageinstance.pk %}">{{ storageinstance.id }}</a></td>
              <td>{{ storageinstance.get_storage_type_display }}</td>
              <td>{{ storageinstance.date_inoculated }}</td>
            </tr>
            {% endfor %}
          {% else %}
            <tr>
              <td colspan="3">No inocualted storage with this yeast</td>
            <tr>
          {% endif %}
        </tbody>
      </table>
    </div>
      <div id="used" class="tab-pane fade">
        <table class="table">
          <thead class="thead-dark">
            <tr>
              <th>Storage ID</th>
              <th>Storage Type</th>
              <th>Date Inoculated</th>
            </tr>
          </thead>
          <tbody>
            {% if yeast.get_used_list %}
              {% for storageinstance in yeast.get_used_list %}
              <tr>
                <td><a href="{% url 'storageinstance-detail' storageinstance.pk %}">{{ storageinstance.id }}</a></td>
                <td>{{ storageinstance.get_storage_type_display }}</td>
                <td>{{ storageinstance.date_inoculated }}</td>
              </tr>
              {% endfor %}
            </ul>
          {% else %}
            <tr>
              <td colspan="3">No used storage with this yeast</td>
            <tr>
          </ul>
          {% endif %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

{% endblock %}